### ISSUE TITLE
prevent collision while writing logs

### ISSUE THREAD

**Issue by Ali-Razmjoo** [viraintel/OWASP-Nettacker#22]
Hello everyone,

While I was testing the frameworks, I notice that sometimes when the modules are writing the logs some collision happens.

```python
save = open(log_in_file, 'a')
save.write(
    json.dumps({'HOST': target, 'USERNAME': user, 'PASSWORD': passwd, 'PORT': port, 'TYPE': 'ssh_brute',
                'DESCRIPTION': messages(language, 66), 'TIME': now(), 'CATEGORY': "brute",
                'SCAN_ID': scan_id, 'SCAN_CMD': scan_cmd}) + '\n')
save.close()
```

it's best to add a function to the core and use it for locking the file and waiting for unlocking and replace all logging with this function.

sample function:
```python
def __log_to_file(filename, mode="a")
	while 1:
		if file not lock:
			lock the file
			write.filename.mode
			unlock the file
			break
		else 
			sleep x.x
	return True
```

Let me know if anyone can help with this.

Regards.

**Comment by ravindra1307** [comment]
i will help you with this.
will you be able to provide me some approach or tips so that i can speed up my work

**Comment by Ali-Razmjoo** [comment]
Hello,

you have to create a function in `core/log.py`, inputs must be the filename, file writing mode (append[`a`], append-byte[`ab`], write[`w`], write-byte[`wb`]), content.

after getting the inputs you must check if the file is lock wait, and if it's not you may lock it (to prevent other processes open it) and write the content.

after that, each write functions should be fixed in the modules, e.g.: tcp_connect_port_scan module [line 128](https://github.com/viraintel/OWASP-Nettacker/blob/master/lib/scan/tcp_connect_port/engine.py#L128)

and it's done!

I think this solution might work: http://tilde.town/~cristo/file-locking-in-python.html
just note that `fcntl` is not available on windows! this might help too (need to be test first). https://pypi.python.org/pypi/portalocker

**Comment by ravindra1307** [comment]
thanks i will soon update the project with this lock feature

**Comment by avhvr** [comment]
Hey, I have a solution that will work on windows too.
Shall I give a try? If so do I need to replace all the write code like save.write(), thread.write(), etc.,

**Comment by Ali-Razmjoo** [comment]
Hello,

I glad if you can share your solution, @ravindra1307  is working on this, feel free to help and push your code.

Regards.

**Comment by Ali-Razmjoo** [comment]
Hello,

Thank you @avhvr, your contribution fixed this issue.

Regards.
