### ISSUE TITLE
Problem in run from other Directories

### ISSUE THREAD

**Issue by ArianPH** [viraintel/OWASP-Nettacker#23]
Hello everyone,

While running this framework on my machine (in MacOS) I've been notice that there is a different between running from "Working Directory" and from other Directories. 

I think its because the framework can't read (find) its own files when "Working Directory" & "Location of Framework" are different; and when framework run from directories which are NOT the working directory, it can't find its own files and causes this problem.

<img width="559" alt="screen shot 2018-01-29 at 9 12 34 pm" src="https://user-images.githubusercontent.com/16976612/35526850-12d664d0-053e-11e8-9f8d-a8dc96ff8e3f.png">
<img width="567" alt="screen shot 2018-01-29 at 9 11 49 pm" src="https://user-images.githubusercontent.com/16976612/35526851-1322e0a8-053e-11e8-80f0-892303d3107d.png">

Let me know if anyone have idea about that.

Regards.

_________________
**OS**: `MacOS`

**OS Version**: `MacOS Sierra`

**Python Version**: `2.7.10`

**Comment by ArianPH** [comment]
Hello everyone,

Solution has been find.

fixing...

Regards.

**Comment by Ali-Razmjoo** [comment]
Hello,

I'd re-open it, Please re-close this after you make your PR.

Regards.

**Comment by ArianPH** [comment]
Hello,

PR has been send.

Regards.

**Comment by Ali-Razmjoo** [comment]
Thank you.
