### ISSUE TITLE
Developers wiki shows core/aler instead of core/alert

### ISSUE THREAD

**Issue by shaddygarg** [viraintel/OWASP-Nettacker#43]
In developers wiki under the Considerations heading(https://github.com/viraintel/OWASP-Nettacker/wiki/Developers#considerations) and alerts subheading, code snippets show `core/aler` instead of `core/alert`. Here is the attached screenshot :

> ![screenshot from 2018-02-14 13-06-55](https://user-images.githubusercontent.com/21990986/36192657-8442e976-1188-11e8-98e3-e406e522c462.png)

**Comment by Ali-Razmjoo** [comment]
Hi,

thanks for noticing, I'll update the wiki soon, the documents also are old and needs to be updated.

Best regards.

**Comment by shaddygarg** [comment]
I tried to correct it myself but Github doesn't support pull requests on wiki and I don't have the editing rights to the main wiki. :)

**Comment by Ali-Razmjoo** [comment]
Hello,

Yes, unfortunately github does not supports PR on wiki.

I'll fix it soon.

regards.

**Comment by Ali-Razmjoo** [comment]
fixed, thanks.
