### ISSUE TITLE
Multiple imports of random in pma_scan module

### ISSUE THREAD

**Issue by shaddygarg** [viraintel/OWASP-Nettacker#44]
The file engine.py in pma_scan module has multiple imports of random https://github.com/viraintel/OWASP-Nettacker/blob/master/lib/scan/pma/engine.py#L10 and https://github.com/viraintel/OWASP-Nettacker/blob/master/lib/scan/pma/engine.py#L12
_________________
**OS**: `Ubuntu`

**OS Version**: `17.10`

**Python Version**: `2.7`

**Comment by Ali-Razmjoo** [comment]
Hello,

Thank you for sharing issue, I'll check it soon.

Regards.

**Comment by Ali-Razmjoo** [comment]
Hey,

I've seen it's importing double, so let me close this issue and check your PR.

Best Regards.
