### ISSUE TITLE
the wizard  looks broken!

### ISSUE THREAD

**Issue by senaps** [viraintel/OWASP-Nettacker#46]
see the image! this is what i saw when i wanted to create a video tutorial on how to use the app.
this is zsh, but i tested with normal bash and had the same result! :)
[image](http://uupload.ir/files/j3hk_screenshot_2018-02-14_18:36:58.png)
_________________
**OS**: `UBUNTU 17.10`

**OS Version**: `17.10`

**Python Version**: `3.6.3`

**Comment by Ali-Razmjoo** [comment]
Hello,

thank you for reporting the issue, please give me some time to review it.

regards.

**Comment by Ali-Razmjoo** [comment]
Hi,

Bug fixed, thank you for your report.

Best Regards.
