### ISSUE TITLE
multiple bugs in the modules

### ISSUE THREAD

**Issue by Ali-Razmjoo** [viraintel/OWASP-Nettacker#48]
Hello,

Thanks to @shaddygarg for the recent contribution on #45, now we can see all of the `vuln`, `scan`, `brute` module have the same bug as `pma_scan`. I glad if anyone would send a fix through the PR.

Best Regards.

**Comment by shaddygarg** [comment]
I will be glad to take up the issue!

**Comment by Ali-Razmjoo** [comment]
Thanks, Done.
