### ISSUE TITLE
Feature Enhancement

### ISSUE THREAD

**Issue by SriHarshaGajavalli** [viraintel/OWASP-Nettacker#51]
Hi,
How about developing Web Application Scanner? If you are looking to have and isn't already available, I am ready to develop it.

**OS**: `Ubuntu`

**OS Version**: `16.04`

**Python Version**: `3.5`

**Comment by Ali-Razmjoo** [comment]
Hello,

Please share more details, do you want to create a web application fuzzer, or crawler or all of them. just in case you looking for suggestions, you can create scanners for specific CMS (wordpress, joomla, vbulletin, drupal, and ....).

feel free to contribute and send PR. 

Regards.

**Comment by SriHarshaGajavalli** [comment]
I will start with Fuzzing technique to scan vulnerabilities of a web app. Crawling can be added to it later.

**Comment by Ali-Razmjoo** [comment]
Hello @SriHarshaGajavalli,

You may use OWASP ZAP API and other OWASP projects to contribute this. I may close this issue, feel free to re-open the issue and send PR after adding a module. just notice that OWASP projects are in priority [[1](https://github.com/zaproxy/zaproxy/wiki/ApiDetails)]

Best Regards.
