### ISSUE TITLE
Issue in stealth scan in port scan

### ISSUE THREAD

**Issue by pradeepjairamani** [viraintel/OWASP-Nettacker#60]
Please Describe the issue or question and share your OS and Python version.
_________________
**OS**: `Linux`

**OS Version**: ` Linux ubuntu 3.13.0-32-generic `

**Python Version**: `2.7.3`

![screenshot from 2018-03-06 01_16_23](https://user-images.githubusercontent.com/24669027/37023969-9dda5e3a-214d-11e8-9e32-c9b757846e82.png)

**Comment by Ali-Razmjoo** [comment]
Hello,

thank you for reporting this bug, BTW you should use `--method-args port_scan_stealth=True`

Best Regards.

**Comment by pradeepjairamani** [comment]
I understand the point but we should use try except for that so the code shouldn't show any errors,
I have resolved the bug in my last commit

**Comment by Ali-Razmjoo** [comment]
Hello,

Please let this discussion be open until we fix the bug. this bug should be fixed in [here](https://github.com/viraintel/OWASP-Nettacker/blob/master/core/args_loader.py#L516), and thank you for your contribution.

Regards.

**Comment by pradeepjairamani** [comment]
Sorry got a little confused there.
I will try to fix the bug here as well 😎

**Comment by Ali-Razmjoo** [comment]
Hello,

I would close it and open a new issue for `args_loader.py` problem.

Best Regards.
