### ISSUE TITLE
Issue with port scan module when using --method-args port_scan_stealth=true

### ISSUE THREAD

**Issue by pradeepjairamani** [viraintel/OWASP-Nettacker#61]
Please Describe the issue or question and share your OS and Python version.
_________________
**OS**: `Linux `

**OS Version**: `Ubuntu`

**Python Version**: `2.7.3`
![screenshot from 2018-03-06 05 48 15](https://user-images.githubusercontent.com/24669027/37035934-212a083c-2174-11e8-94dd-47c7d5520322.png)

**Comment by pradeepjairamani** [comment]
These lines are creating the error because there isn't any conf file to import these variables

 conf.verb = 0
 conf.nofilter = 1

After Removing them the scanner doesn't perform port scanning.
![screenshot from 2018-03-06 06 21 01](https://user-images.githubusercontent.com/24669027/37037199-c9e4d044-2177-11e8-9bf5-88e05aa40a6c.png)

**Comment by Ali-Razmjoo** [comment]
Hello,

Thank you for reporting this issue, let me check it and get back to you.

Best Regards.

**Comment by Ali-Razmjoo** [comment]
Hello,

could you please enter these codes in python console and get me the results, I don't get any error!

```python
from scapy.all import *
conf.verb = 0
conf.nofilter = 1
```

BTW I've tested it on python `2.7.13`, maybe it's because you are using `2.7.3` ?

Regards.

**Comment by pradeepjairamani** [comment]
Sorry, it was a mistake on my side. There were some errors with scapy which are now resolved and it's working fine.
Closing this issue.

Best Regards
Pradeep Jairamani
