### ISSUE TITLE
New language library

### ISSUE THREAD

**Issue by Ali-Razmjoo** [viraintel/OWASP-Nettacker#65]
Hello,

As the framework is growing, I think the existing language library I created to keep the message is not good enough for a bigger framework, using numbers make conflicts in PRs. I think it's better to change it before framework gets bigger.

my idea is, use the same libs structure, but use messages instead of numbers.

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-


def all_messages():
    """
    keep all messages in en
    Returns:
        all messages in JSON
    """
    return \
        {
            "start_message": "Nettacker engine started ...\n\n",
            "help_options": "python nettacker.py [options]",
            "help_menu": "Show Nettacker Help Menu",
             etc...
        }

```

let me know if anyone would like to work on this. it has **priority** to fix and update documentation.

Best Regards.

**Comment by pradeepjairamani** [comment]
I understand the point and I am willing to help with this. Do I have to create those messages myself or will you give me the details because there are 180 total messages, and what about the different languages? Do I need to do this for all the languages or just english?

**Comment by Ali-Razmjoo** [comment]
Hello,

thank you for your question, no English is in priority, also it just needs to change the identifier number, and find the message in the framework and replace it.
e.g.
```
message(language, "start_message")
```

Regards.

**Comment by pradeepjairamani** [comment]
I am having a little trouble understanding the problem.

like for example, we are giving numbers (1-180) for messages in our current method for fetching data from languages, you want me to change them from 
def all_messages():
 ``   return 
        {
            "0": "Nettacker engine started ...\n\n",
            "1": "python nettacker.py [options]",
            "2": "Show Nettacker Help Menu",
            "3": "Please read license and agreements https://github.com/viraint$
            "4": "Engine",
            "5": "Engine input options",
            "6": "select a language {0}",
            "7": "scan all IPs in the range",
}``

to

``   return 
        {
            "scan_started": "Nettacker engine started ...\n\n",
            "options": "python nettacker.py [options]",
            "help_menu": "Show Nettacker Help Menu",
            "license": "Please read license and agreements https://github.com/viraint$
            "engine": "Engine",
            "input_options": "Engine input options",
            "select_lang": "select a language {0}",
            "scan_ip_ranges": "scan all IPs in the range",
}``

in all the libraries as well as in the /lib/language/messages_en.py

so can I add those names scan_started, options, help_menu, license, etc. by myself or do I need to follow any method?

Best Regards

**Comment by Ali-Razmjoo** [comment]
Hey,

if you mean choosing an id name, yes you may do it yourself, there are no any methods, just you may see what are they about and change them.

your example is also fine.

```
return { "scan_started": "Nettacker engine started ...\n\n", "options": "python nettacker.py [options]", "help_menu": "Show Nettacker Help Menu", "license": "Please read license and agreements https://github.com/viraint$ "engine": "Engine", "input_options": "Engine input options", "select_lang": "select a language {0}", "scan_ip_ranges": "scan all IPs in the range", }
```

Thanks.

**Comment by pradeepjairamani** [comment]
ok, I will solve this issue as soon as I can.

Best Regards

**Comment by Ali-Razmjoo** [comment]
Thank you @pradeepjairamani. fixed.

**Comment by Ali-Razmjoo** [comment]
Hey,

I applied changes to all languages lib using google translate API, I will open a new issue to get help from contributors to upgrade the quality of the messages
