### ISSUE TITLE
Module Wappalyzer Scan is not Available

### ISSUE THREAD

**Issue by pradeepjairamani** [viraintel/OWASP-Nettacker#67]
![screenshot_16](https://user-images.githubusercontent.com/24669027/37253462-165f6072-2558-11e8-8635-26f512934a10.png)
Please Describe the issue or question and share your OS and Python version.
_________________
**OS**: `Linux`

**OS Version**: `Linux ubuntu`

**Python Version**: `2.7.3`

**Comment by shaddygarg** [comment]
I cloned the master and the module is running fine on my system :
![screenshot from 2018-03-11 18-24-19](https://user-images.githubusercontent.com/21990986/37253611-020c4d22-255a-11e8-8e01-d68236148c4b.png)
Perhaps you don't have bs4 installed into your system.

**Comment by pradeepjairamani** [comment]
Yes, I have also used "master" for testing it again please check if any modules are needed which are available in your system for running wapalyzer but not present in requirements.txt 

Bes Regards
Pradeep Jairamani

**Comment by shaddygarg** [comment]
No, only bs4 is required for running this
Regards.

**Comment by pradeepjairamani** [comment]
Hello,

I am able to run it on a windows system but fail to run it on a Linux system, can you please confirm?

Best Regards
Pradeep Jairamani

**Comment by pradeepjairamani** [comment]
Hello

Sorry, There was an issue with my system. I installed BeautifulSoup instead of BS4.
Please edit the requirements.txt file.

Best Regards
Pradeep Jairamani

**Comment by Ali-Razmjoo** [comment]
Hello,

Thanks for your contributions, should I mark it as fixed and close it?

Regards.

**Comment by shaddygarg** [comment]
Yes, I have updated the requirements in the latest PR. This issue is fixed!!

**Comment by Ali-Razmjoo** [comment]
Thank you, issue closed.
