### ISSUE TITLE
Index Error in http_basic_auth

### ISSUE THREAD

**Issue by pradeepjairamani** [viraintel/OWASP-Nettacker#68]
Please Describe the issue or question and share your OS and Python version.
_________________
**OS**: `Linux`

**OS Version**: `Linux ubuntu`

**Python Version**: `2.7.3`
![screenshot_15](https://user-images.githubusercontent.com/24669027/37253479-3251108c-2558-11e8-8262-2660a69af6ac.png)

**Comment by shaddygarg** [comment]
Hey @pradeepjairamani,
I am unable to reproduce the issue. Can you tell me the command which you used to generate this error?
Regards

**Comment by pradeepjairamani** [comment]
Sorry, @shaddygarg  I am also unable to reproduce the issue and I also forgot which command I had used when this issue came.
give me a few days if I can't reproduce this bug, we will close it.

Best Regards
Pradeep Jairamani

**Comment by Ali-Razmjoo** [comment]
Hello,

I cannot find any bugs either. in a few days, I will test and emulate all modules recently added to the framework to find the bugs.

Regards.
