### ISSUE TITLE
framework false target input check

### ISSUE THREAD

**Issue by Ali-Razmjoo** [viraintel/OWASP-Nettacker#74]
Hello,

It seems there is a bug in target types (#66), this bug came from `core/targets.py` [[1](https://github.com/viraintel/OWASP-Nettacker/blob/master/core/targets.py)]. feel free to contribute to this and send your PR.

Best Regards.

**Comment by shaddygarg** [comment]
Hey,
I would like to work on solving this bug and will soon send a PR. 
Regards

**Comment by shaddygarg** [comment]
Hey @Ali-Razmjoo,
I think that the issue can be closed. Can you tell me if there is still any issue that remains unaddressed?
Regards

**Comment by Ali-Razmjoo** [comment]
Hey,

there was a simple [bug](https://github.com/viraintel/OWASP-Nettacker/commit/7254a096192ff0d9069f88b7c52912c12f3a3729) which I just fixed. `re.match('^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$', 't')` changed to `re.match('^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$', t):`,
 (removed `'t'`). thanks for contribution. I may close it now.

Regards.

**Comment by shaddygarg** [comment]
Oh, I get it. thanks for the informaton.
Regards.
