### ISSUE TITLE
args_loader upgrade

### ISSUE THREAD

**Issue by Ali-Razmjoo** [viraintel/OWASP-Nettacker#75]
Hello,

according to #60 issue, the `core/args_loader.py` is not working well and does not consider all possible commands. we can add a task to replace `--method-args port_scan_stealth` with `--method-args port_scan_stealth=True`. the default values for any `key` would be `True`.

e.g. `--method-args port_scan_stealth&port_scan_ports=1,2,3&dir_scan_random_agent` would be equal to `--method-args port_scan_stealth=True&port_scan_ports=1,2,3&dir_scan_random_agent=True`

let me know if anyone would like to work on this.

Best Regards.

**Comment by pradeepjairamani** [comment]
I tried understanding the code but I couldn't connect it

**Comment by Ali-Razmjoo** [comment]
Hey,

@pradeepjairamani I will take care of this.

thanks.

**Comment by Ali-Razmjoo** [comment]
Fixed.
