### ISSUE TITLE
Version upgrade file showing errors

### ISSUE THREAD

**Issue by pradeepjairamani** [viraintel/OWASP-Nettacker#77]
Please Describe the issue or question and share your OS and Python version.

http://nettacker.z3r0d4y.com/version.py
the link which is used for checking the latest version of nettacker is throwing an error!

Header Info- 
User-Agent : OWASP Nettacker

![screenshot_19](https://user-images.githubusercontent.com/24669027/37257328-463ebfd2-258e-11e8-9436-0d06f69ee52c.png)

**Comment by Ali-Razmjoo** [comment]
Hello,

there is an error on the server, it's checking the old file (version in the main file) I'll fix it soon.

Regards.

**Comment by Ali-Razmjoo** [comment]
Hey,

Fix, thanks for reporting.

Regards.
