### ISSUE TITLE
Stealth Flag referenced before assignment

### ISSUE THREAD

**Issue by pradeepjairamani** [viraintel/OWASP-Nettacker#83]
Please Describe the issue or question and share your OS and Python version.
_________________
**OS**: `Linu`

**OS Version**: `Ubuntu`

**Python Version**: `2.7.3`

![screenshot_20](https://user-images.githubusercontent.com/24669027/37269359-fc818fe8-25ef-11e8-8ca2-d384154f0bed.png)

**Comment by Ali-Razmjoo** [comment]
Hi,

thanks for your report, the last commit must be fixed it. feel free to re-open the issue if it's still having an error.

Best Regards.
